repos:
  -   repo: https://github.com/python/black.git
      rev: 23.7.0
      hooks:
        - id: black
          language_version: python3.11
  -   repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
  -   repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
        -   id: flake8
            additional_dependencies:
              - flake8-alphabetize
              - flake8-annotations
              - flake8-comments
              - flake8-comprehensions
              - flake8-docstrings
              - flake8-expression-complexity
              - flake8-functions
              - flake8-literal
              - flake8-print
              - flake8-pyproject
              - flake8-requirements
              - flake8-tidy-imports
              - flake8-use-fstring
              - flake8-unused-arguments
              - flake8-variables-names
              - pep8-naming
  -   repo: local
      hooks:
        -   id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.5.1
      hooks:
        -   id: mypy
            additional_dependencies:
              - types-requests
              - types-python-dateutil
