name: Noko Client

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-checks:
    runs-on: ubuntu-latest
    name: Static Checks
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then
          pip install -r requirements-dev.txt
          else
          echo "requirements-dev.txt file not found."
          exit 1
          fi

      - name: Formatting Black
        run: black --check .
      - name: Lint Flake8
        run: flake8 .
      - name: Analyse Pylint
        run: pylint $(git ls-files '*.py')
      - name: Static Type Check mypy
        run: mypy $(git ls-files '*.py')
